### ISSUE TITLE
Cannot Use DHCP mode

### ISSUE THREAD

**Issue by wsy** [bundyfx/NanoBuilder#1]
I want to use DHCP mode for my NanoServer.
So I left the three related fields blank. (IPv4 Address, IPv4 Gateway, IPv4 Subnet Mask).
Then the script tells me I did not input a valid IPv4 Address and give me a regular expression.

If we shall input 0.0.0.0 to use DHCP, you shall change the variable from $null to "0.0.0.0".
Otherwise, you shall remove these three fields from $NanoProps if they're $null

**Comment by bundyfx** [comment]
Hi wsy, I've decided to depreciate this project as this was more of a personal/learning project from 2015. I think there are more efficient ways to create Nano Server images for on-prem deployments such as build servers triggered from github yaml file (just an example).

Many thanks!
